// vibecode-starters/nextjs-new/app/page.tsx
export default function Page() {
  return (
    <main style={{ padding: 24 }}>
      <h1>@vibecode-starters/nextjs-new</h1>
      <p>Next.js 15 App Router starter is running.</p>
    </main>
  );
}

export default function Home() {
  return (
    <main className='flex min-h-screen flex-col items-center justify-between p-24'>
      <div className='z-10 max-w-5xl w-full items-center justify-between font-mono text-sm lg:flex'>
        <h1 className='text-4xl font-bold text-center'>Welcome to Next.js!</h1>
      </div>

      <div className='relative flex place-items-center'>
        <p className='text-lg'>Start building your amazing Next.js application.</p>
      </div>
    </main>
  );
}

// vibecode-starters/vue/src/App.vue
<template>
  <div style="padding:24px">
    <h1>@vibecode-starters/vue</h1>
    <p>Vue 3 + Vite + TypeScript starter is running.</p>
  </div>
  
</template>

<script setup lang="ts">
</script>

<template>
  <div id="app">
    <header>
      <h1>Welcome to Vue.js!</h1>
      <p>Start building your amazing Vue application.</p>
    </header>
    <main>
      <div class="card">
        <h2>Vue 3 + Vite</h2>
        <p>This is a simple Vue.js starter template.</p>
      </div>
    </main>
  </div>
</template>

<script>
export default {
  name: 'App',
};
</script>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}

.card {
  padding: 20px;
  margin: 20px;
  border: 1px solid #ddd;
  border-radius: 8px;
  background-color: #f9f9f9;
}
</style>
