// vibecode-starters/angular/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  standalone: true,
  template: `
    <div style="padding:24px">
      <h1>@vibecode-starters/angular</h1>
      <p>Angular starter is running.</p>
    </div>
  `,
})
export class AppComponent {}

import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { RouterOutlet } from '@angular/router';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule, RouterOutlet],
  template: `
    <div class="container">
      <header>
        <h1>Welcome to Angular!</h1>
        <p>Start building your amazing Angular application.</p>
      </header>
      <main>
        <div class="card">
          <h2>Angular 16</h2>
          <p>This is a simple Angular starter template.</p>
        </div>
      </main>
      <router-outlet></router-outlet>
    </div>
  `,
  styles: [
    `
      .container {
        font-family: Arial, sans-serif;
        text-align: center;
        margin: 20px;
      }
      .card {
        padding: 20px;
        margin: 20px;
        border: 1px solid #ddd;
        border-radius: 8px;
        background-color: #f9f9f9;
      }
    `,
  ],
})
export class AppComponent {
  title = 'angular-starter';
}

// vibecode-starters/vue/src/App.vue
<template>
  <div style="padding:24px">
    <h1>@vibecode-starters/vue</h1>
    <p>Vue 3 + Vite + TypeScript starter is running.</p>
  </div>
  
</template>

<script setup lang="ts">
</script>

<template>
  <div id="app">
    <header>
      <h1>Welcome to Vue.js!</h1>
      <p>Start building your amazing Vue application.</p>
    </header>
    <main>
      <div class="card">
        <h2>Vue 3 + Vite</h2>
        <p>This is a simple Vue.js starter template.</p>
      </div>
    </main>
  </div>
</template>

<script>
export default {
  name: 'App',
};
</script>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}

.card {
  padding: 20px;
  margin: 20px;
  border: 1px solid #ddd;
  border-radius: 8px;
  background-color: #f9f9f9;
}
</style>
